spring:
   security:
      user:
         name: admin
         password: admin
   datasource:
      url: jdbc:h2:mem:testdb
      username: admin
      password: admin
      driverClassName: org.h2.Driver

   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
   mvc:
      servlet:
         path: /api
   jackson:
      serialization:
         WRITE_DATES_AS_TIMESTAMPS: false
server:
   servlet:
      contextPath: /FASA

hibernate:
   dialect: org.hibernate.dialect.H2Dialect
