spring:
    security:
        user:
            name: admin
            password: admin

    datasource:
        url: jdbc:h2:mem:testdb
        username: admin
        password: admin
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
