CREATE SCHEMA EXPENSE_TRACKER;

CREATE TABLE  EXPENSE_TRACKER.EXPENSE (
	EXPENSE_ID int,
	EXPENSE_VERSION int,
	EXPENSE_VALUE DECIMAL(9,2),
	EXPENSE_CURRENCY varchar(3),
	EXPENSE_REASON varchar(255),
	EXPENSE_DATE date,
	EXPENSE_ORIGINAL_VALUE DECIMAL(9,2),
	EXPENSE_ORIGINAL_CURRENCY varchar(3),
	EXPENSE_EXCHANGE_RATE DECIMAL(3,2),
	EXPENSE_CREATED_TIMESTAMP date,
	EXPENSE_UPDATED_TIMESTAMP date
);
ALTER TABLE EXPENSE_TRACKER.EXPENSE MODIFY COLUMN EXPENSE_ID INT auto_increment;

CREATE TABLE  EXPENSE_TRACKER.TAG (
	TAG_ID int,
	TAG_VERSION int,
	TAG_NAME varchar(255),
	TAG_CREATED_TIMESTAMP date,
	TAG_UPDATED_TIMESTAMP date
);
ALTER TABLE EXPENSE_TRACKER.TAG MODIFY COLUMN TAG_ID INT auto_increment;

CREATE TABLE EXPENSE_TRACKER.EXPENSE_TAGS (
	EXPENSE_ID int,
	TAG_ID int
);

CREATE TABLE EXPENSE_TRACKER.EXCHANGE (
	EXCHANGE_ID int,
	EXCHANGE_VERSION int,
	EXCHANGE_BASE varchar(3),
	EXCHANGE_SYMBOL varchar(3),
	EXCHANGE_RATE DECIMAL(3,2),
	EXCHANGE_DATE date,
	EXCHANGE_CREATED_TIMESTAMP date,
	EXCHANGE_UPDATED_TIMESTAMP date
);
ALTER TABLE EXPENSE_TRACKER.EXCHANGE MODIFY COLUMN EXCHANGE_ID INT auto_increment;
