create table TAG(
  TAG_ID               	    		integer NOT NULL PRIMARY KEY,
  TAG_VERSION			  			integer NOT NULL, 
  TAG_NAME							varchar(50) NOT NULL,
  TAG_CREATED_TIMESTAMP 			date NOT NULL,
  TAG_UPDATED_TIMESTAMP 			date,
);

create table EXCHANGE(
  EXCHANGE_ID						integer NOT NULL PRIMARY KEY,
  EXCHANGE_VERSION					integer NOT NULL, 
  EXCHANGE_BASE_CURRENCY			varchar(3) NOT NULL,
  EXCHANGE_DESTINATION_CURRENCY 	varchar(3) NOT NULL,
  EXCHANGE_RATE 					FLOAT NOT NULL,
  EXCHANGE_CREATED_TIMESTAMP		date NOT NULL,
  EXCHANGE_UPDATED_TIMESTAMP		date,
);

create table INCOME(
  INCOME_ID							integer NOT NULL PRIMARY KEY,
  INCOME_VERSION					integer NOT NULL, 
  INCOME_YEARLY_GROSS_INCOME		FLOAT NOT NULL,
  INCOME_YEARLY_NET_INCOME		 	FLOAT NOT NULL,
  INCOME_MONTHLY_GROSS_INCOME		FLOAT NOT NULL,
  INCOME_MONTHLY_NET_INCOME			FLOAT NOT NULL,
  INCOME_CREATED_TIMESTAMP			date NOT NULL,
  INCOME_UPDATED_TIMESTAMP			date,
);

create table EXPENSE(
  EXPENSE_ID						integer NOT NULL PRIMARY KEY,
  EXPENSE_VERSION					integer NOT NULL, 
  EXPENSE_VALUE						FLOAT NOT NULL,
  EXPENSE_DESCRIPTION			 	varchar(100) NOT NULL,
  EXPENSE_DATE						date NOT NULL,
  EXPENSE_ORIGINAL_VALUE			FLOAT,
  EXPENSE_ORIGINAL_CURRENCY			varchar(3),
  EXPENSE_TAG_ID					integer NOT NULL REFERENCES TAG(TAG_ID) ON DELETE RESTRICT,
  EXPENSE_CREATED_TIMESTAMP			date NOT NULL,
  EXPENSE_UPDATED_TIMESTAMP			date,
  
);